GET http://localhost:3000/users

###
POST  http://localhost:3000/add
content-Type: application/json

{  "name":"hameda",
   "email":"hameda@gmail.com",
   "adress":"turkey"
}
###
PUT  http://localhost:3000/63cd6595bb8c00d93669145a
content-Type: application/json

{
    "name":"med"
}

###
DELETE http://localhost:3000/63cd838eec713b379deb1456